name: Hello World Workflow

on: [push]

jobs:
  say-hi-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hi
        run: echo "Hello, world!"
      - name: Say List the Files
        run: ls
      - name: Show the location
        run: pwd  